server:
  port: 8080
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true #使用小写service-id
      routes: #配置路由路径
        - id: mall-service-auth
          uri: lb://mall-service-auth
          predicates:
            - Path=/mall-service-auth/**
          filters:
            - StripPrefix=1
        - id: mall-service-user
          uri: lb://mall-service-user
          predicates:
            - Path=/mall-service-user/**
          filters:
            - StripPrefix=1
        - id: mall-service-goods
          uri: lb://mall-service-goods
          predicates:
            - Path=/mall-service-goods/**
          filters:
            - StripPrefix=1
        - id: mall-service-order
          uri: lb://mall-service-order
          predicates:
            - Path=/mall-service-order/**
          filters:
            - StripPrefix=1
        - id: mall-service-context
          uri: lb://mall-service-context
          predicates:
            - Path=/mall-service-context/**
          filters:
            - StripPrefix=1
        - id: mall-service-context
          uri: lb://mall-service-portal
          predicates:
            - Path=/mall-service-portal/**
          filters:
            - StripPrefix=1
        - id: mall-search
          uri: lb://mall-search
          predicates:
            - Path=/mall-search/**
          filters:
            - StripPrefix=1
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: 'http://localhost:8080/mall-service-auth/rsa/publicKey' #配置RSA的公钥访问地址
  redis:
    database: 0
    port: 6379
    host: 192.168.8.137
    password: 123456
secure:
  ignore:
    urls: #配置白名单路径
      - "/doc.html"
      - "/swagger-resources/**"
      - "/swagger/**"
      - "/**/v2/api-docs"
      - "/**/*.js"
      - "/**/*.css"
      - "/**/*.png"
      - "/**/*.ico"
      - "/webjars/springfox-swagger-ui/**"
      - "/actuator/**"
      - "/mall-service-auth/oauth/token"
      - "/mall-service-auth/rsa/publicKey"
      - "/mall-search/**"
      - "/mall-service-portal/sso/login"
      - "/mall-service-portal/sso/register"
      - "/mall-service-portal/sso/getAuthCode"
      - "/mall-service-portal/home/**"
      - "/mall-service-portal/product/**"
      - "/mall-service-portal/brand/**"
      - "/mall-service-user/admin/login"
      - "/mall-service-user/admin/register"
      - "/mall-service-file/minio/upload"
management: #开启SpringBoot Admin的监控
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
logging:
  config: classpath:logback-spring.xml
